version: '3'
services:
    redis:
        build: ./trendmap/redis/
        container_name: redis
        networks:
            - trendmap-docker-net
    backend:
        build: ./trendmap/backend/
        container_name: backend
        depends_on: 
            - redis
        networks:
            - trendmap-docker-net
    frontend:
        build: ./trendmap/frontend/
        container_name: frontend
        ports:
            - "80:3000"
        depends_on: 
            - backend
        networks:
            - trendmap-docker-net
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./server/nginx-conf:/etc/nginx/conf.d
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
        depends_on:
            - frontend
        networks:
            - trendmap-docker-net
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
        depends_on: 
            - nginx
        command: certonly --webroot --webroot-path=/var/www/html --email kostya.iliouk@hotmail.com --agree-tos --no-eff-email --staging -d trendmap.live  -d www.trendmap.live
volumes:
    certbot-etc:
    certbot-var:
    
networks:
    trendmap-docker-net:
        driver: bridge
