version: '3'
services:
    backend:
        build: ./trendmap/backend/
    frontend:
        build: ./trendmap/frontend/
        ports:
            - "3000:3000"
    redis:
        build: ./trendmap/redis/